name: Invitation to the Glasgow Azure User Group Github community
description: I would like to be part of the Glasgow Azure User Group Github community
title: "Please invite me to the Glasgow Azure User Group Github community"
labels: [invite]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true
  - type: textarea
    id: Additional
    attributes:
      label: Additional Context
      description: Why do you want to join?
    validations:
      required: true
 
