name: Speaker
description: Use this form to volunteer to speak at a Glasgow Azure User Group meetup. 
title: "[Speaking]: "
labels: ["speaker"]
assignees:
  - weeyin83
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: SesstionTitle
    attributes:
      label: Session Title
      description: What is the title of the session you'd like to present?
    validations:
      required: true
  - type: textarea
    id: SessionDetails
    attributes:
      label: Session Details
      description: What is your session about?
      render: shell
